services:
  db:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cryptodb
      MYSQL_ROOT_PASSWORD: cryp70db_s3cr37
      MYSQL_USER: checkoutuser
      MYSQL_PASSWORD: ch3ckpo1nt_t1cket
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravelnet

networks:
  laravelnet:

volumes:
  mysql_data: